name: panshop_driver
description: Panshop Driver
publish_to: none

version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  get: ^4.6.5
  get_storage: ^2.1.1
  flutter_screenutil: ^5.0.0+2
  dartz: ^0.10.1
  panda_map: 
    git: https://github.com/dttrung-99931/PandaMap.git

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

dependency_overrides:
  here_sdk:
    path: pluggins/heresdk-explore-flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
